apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: httpd
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
        - name: httpd
          image: httpd
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: httpd-service
  labels:
    name: httpd-service
spec:
  ports:
    - port: 8009
      targetPort: 80
      protocol: TCP
  selector:
    app: httpd
  type: ClusterIP